# Generated by Django 2.2 on 2020-09-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='default note', max_length=25),
            preserve_default=False,
        ),
    ]
